version: "3.8"

services:
  booking-api:
    build: .
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - TOKEN_EXPPIRES=${TOKEN_EXPPIRES}
      - TOKEN_TYPE=${TOKEN_TYPE}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
        - db
  
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
  

