version: "3.8"

services:
  booking-api:
    build: .
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - TOKEN_EXPPIRES=${TOKEN_EXPPIRES}
      - TOKEN_TYPE=${TOKEN_TYPE}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-network
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:${PORT} || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
    networks:
      - db-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo db:27017/speech-api --quiet
      interval: 30s
      timeout: 10s
      retries: 5
  

#Docker Networks
networks:
  db-network:
    driver: bridge
